name: tela
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  google_maps_flutter: ^0.5.33
  geolocator: ^6.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: 

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/pasta.jpeg
    - assets/image/livreseLogo.png
    - assets/image/fahrenheit451.png
    - assets/image/mapa.jpeg
    - assets/image/livros.jpeg
    - assets/image/avatarTcc.png
    - assets/image/fundoTcc.jpg
    - assets/image/codigodavinci.jpg
    - assets/image/1984.jpg
    - assets/image/poder.jpg
    - assets/image/rainha.jpg
    - assets/image/dom-quixote.jpg
    - assets/image/viagemaocentro.jpg
    - assets/image/osenhor.jpg
    - assets/image/ailha.jpg
    - assets/image/perfeito.jpg
    - assets/image/theupside.jpg
    - assets/image/aquimica.jpg
    - assets/image/todasflores.jpg
    - assets/image/annefrank.jpg
    - assets/image/steve.jpg
    - assets/image/malala.jpeg
    - assets/image/minhahistoria.jpg
    - assets/image/ummilhao.jpg
    - assets/image/call.jpg
    - assets/image/oterceiro.jpg
    - assets/image/vermelho.jpg
    - assets/image/haikyuu.jpg
    - assets/image/naruto.jpg
    - assets/image/attack.jpg
    - assets/image/boruto.jpg
    - assets/image/serial.jpg
    - assets/image/abc.jpg
    - assets/image/sanguefrio.jpg
    - assets/image/killer.jpg
    - assets/image/it.jpg
    - assets/image/frank.jpg
    - assets/image/dracula.jpg
    - assets/image/exorcista.jpg

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
